header:
  version: 18
  includes:
    -Kas/include/local.yml
    -Kas/include/oe.yml
machine: qemux86-64
distro: tech-distro
build_system: oe
target: core-image-base
repos:
  meta_raspberrypi:
    url: "https://github.com/agherzan/meta-raspberrypi.git"
    path: "/home/hamza/yocto/layers/meta-raspberrypi"
    branch: "scarthgap"
  meta-tech-distro:
    path: "../meta-tech-distro"
  meta-tech-bsp:
    path: "../meta-tech-bsp"
  meta-tech-prj:
    path: "../meta-tech-prj"
    

        
        


        

